# Generated by Django 6.0.3 on 2026-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
